pipeline {
    agent {
        label 'docker-agent-node'
    }

    options {
        skipDefaultCheckout(true)

        timestamps()

        disableConcurrentBuilds()

        timeout(
            time: 2,
            unit: 'MINUTES'
        )

        buildDiscarder(
            logRotator(
                numToKeepStr: '30'
            )
        )
    }

    environment {
        APPLICATION_NAME = 'main-client'
        APPLICATION_DIRECTORY = 'clients/main'
        DOCKER_DIRECTORY = 'clients/main/jenkins'
        DOCKER_IMAGE = 'smit9924/frontend/main-client'
    }

    stages {

        stage('Initialize') {

            steps {

                script {

                    if (!params.SOURCE_BRANCH?.trim()) {
                        error('SOURCE_BRANCH must not be empty.')
                    }

                    env.SOURCE_BRANCH =
                        params.SOURCE_BRANCH.trim()

                    currentBuild.displayName =
                        "#${env.BUILD_NUMBER} ${env.SOURCE_BRANCH}"

                    currentBuild.description =
                        "Application: ${env.APPLICATION_NAME}"
                }
            }
        }

        // Checkout

        // Build

        // Push
    }
}